[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0xb4079627ebab1cd3cf9fd075dda1ad2454a7a448bf659591f259efa2519b18"
transaction_hash = "0x3a729aa09b4ad351fbc724f94c6d599037a53d7d9b5a182097a60fb09d0486c"
block_number = 3
seed = "dojo_starter"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x3610b797baec740e2fa25ae90b4a57d92b04f48a1fdbae1ae203eaf9723c1a0"
class_hash = "0x198019c07492a87f7b2af983dd4d2353d1d11358b70de6f80ebf3f2f5f6ed6a"
original_class_hash = "0x198019c07492a87f7b2af983dd4d2353d1d11358b70de6f80ebf3f2f5f6ed6a"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x2a92b2db1ea5adaaf713693b9a4d426a95f87471fb025125f86ffd0d2ae4fd2"
original_class_hash = "0x2a92b2db1ea5adaaf713693b9a4d426a95f87471fb025125f86ffd0d2ae4fd2"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_directions_available.json"
name = "dojo_starter::models::directions_available"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "directions"
type = "Array<Direction>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3877a660dff7e1d709e3956bb60e0bfd4ba9884383d3f6d357390481f481a24"
original_class_hash = "0x3877a660dff7e1d709e3956bb60e0bfd4ba9884383d3f6d357390481f481a24"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_moves.json"
name = "dojo_starter::models::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models.members]]
name = "can_move"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7f7ce6b26ee4fce05ef9a759ece6c109d76213fed2a3b22f011f1e89099904"
original_class_hash = "0x7f7ce6b26ee4fce05ef9a759ece6c109d76213fed2a3b22f011f1e89099904"
abi = "manifests/dev/abis/deployments/models/dojo_starter_models_position.json"
name = "dojo_starter::models::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x45fc1c2d4b2e654f128929c123162feab952f9b3aaaa0f47c616a934856d396"
original_class_hash = "0x45fc1c2d4b2e654f128929c123162feab952f9b3aaaa0f47c616a934856d396"
abi = "manifests/dev/abis/deployments/models/dojo_starter_systems_actions_actions_moved.json"
name = "dojo_starter::systems::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false
