kind = "DojoModel"
class_hash = "0x2a92b2db1ea5adaaf713693b9a4d426a95f87471fb025125f86ffd0d2ae4fd2"
original_class_hash = "0x2a92b2db1ea5adaaf713693b9a4d426a95f87471fb025125f86ffd0d2ae4fd2"
abi = "manifests/dev/abis/base/models/dojo_starter_models_directions_available.json"
name = "dojo_starter::models::directions_available"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
